### ISSUE TITLE
Is ZeroConf support from Log4j 1 still relevant?

### ISSUE THREAD

**Issue by vy** [apache/logging-chainsaw#24]
If not (and in particular, given Log4j 1 is EOLed) I would appreciate it if you can remove the relevant sources and documentation.

**Comment by grobmeier** [comment]
Apparantely, ZeroConf appears to be a Log4j2 feature:
https://logging.apache.org/log4j/2.x/manual/configuration.html#chainsaw-can-automatically-process-your-log-files-advertising-ap
